### PR TITLE
2845 Replace all text references to "OMX"

### PR DESCRIPTION
**Pull request by JorgePadilla**
JIRA-2845

### CODE REVIEW

**Review by mmallet-morningstar — APPROVED** [review]
Good work! I'm approving this, but I have one suggestion that could be used or not.

In most articles when reference a naming like this, the abbreviated instance would be included at the first point where it is reference like this: EAP (ESG Assessment Platform). Thereafter in every other case below it will only be references as EAP. 

You don't have to change this if you don't want.

**Review by kreigne-morningstar — APPROVED** [review]
LGTM

**Comment by kreigne-morningstar** [comment]
> Good work! I'm approving this, but I have one suggestion that could be used or not.
> 
> In most articles when reference a naming like this, the abbreviated instance would be included at the first point where it is reference like this: EAP (ESG Assessment Platform). Thereafter in every other case below it will only be references as EAP.
> 
> You don't have to change this if you don't want.

**Comment by kreigne-morningstar** [comment]
Sorry, closed by accident, reopened.

**Review by mmallet-morningstar — APPROVED** [review]
:shipit:

**Pull request merged**
